### PR TITLE
Remove all code

### PR DESCRIPTION
**Pull request by AmjadHD**
This plugin should only provide simple syntax definitions and completions. Other features should be delegated to language servers (nimlsp and nimlangserver).
@Varriount, What do you think ?

### CODE REVIEW

**Comment by AmjadHD** [comment]
ping @Varriount.

**Comment by AmjadHD** [comment]
cc @Varriount.

**Comment by AmjadHD** [comment]
@Varriount.

**Comment by AmjadHD** [comment]
@Varriount

**Comment by AmjadHD** [comment]
@Varriount, Make up your mind.

**Comment by Varriount** [comment]
There is still coffee that is useful and serves a purpose, so no.

**Comment by AmjadHD** [comment]
Which code ?

**Comment by Varriount** [comment]
- https://github.com/nim-lang/NimLime/blob/master/core/commands/hotkeys.py
- https://github.com/nim-lang/NimLime/blob/master/core/commands/nimcheck.py
- https://github.com/nim-lang/NimLime/blob/master/core/commands/project.py

These can be removed if and only if their functionality is currently implemented in other Nim language extensions that are compatible with Sublime Text

**Comment by AmjadHD** [comment]
@Varriount, Aside from hotkeys, these never worked for me.
for hotkeys, just include a `Preferences.sublime-settings` file with these contents:
```json
{
    "doccontinue.enabled": true,
    "doccontinue.autostop": true
}
```
and tell the users they can override them in their own `User/Preferences.sublime-settings`.

**Comment by AmjadHD** [comment]
@Varriount nimcheck.py functionalities is provided by language servers. for project.py, nimble's cli is simple enough for users, they can simply launch a terminal window and type the commands.

**Comment by AmjadHD** [comment]
@Varriount, I need your comment on this.

**Pull request merged**
